language: python
python:
  - 2.7
  - 3.7
branches:
  only:
    - master
install:
  - pip install coverage
  - pip install coveralls
  - pip install pycodestyle
  - pip install -r requirements.txt
script:
  - pycodestyle --max-line-length 119 lambdafy
  - coverage run -m unittest discover lambdafy
  - python setup.py bdist_wheel
after_success:
  - coverage report
  - coveralls
